version: '3.9'
services:
  app_server:
    restart: on-failure
    image: node:alpine
    container_name: mars-project
    working_dir: /app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: sh -c 'yarn install && yarn dev'